#!/bin/sh

case "$1" in
	true) # Enable power saving settings on battery
	  # bus
	  for i in /sys/bus/*/devices/*/power/control; do echo auto > $i; done
	  # usb autosuspend
	  for i in /sys/bus/usb/devices/*/power/autosuspend; do echo 10 > $i; done
	  for i in /sys/bus/usb/devices/*/power/control; do echo auto > $i; done
	  # nmi_watchdog - disabled at kernel
	  #echo 0 > /proc/sys/kernel/nmi_watchdog
	  # cpu
	  for i in /sys/devices/system/cpu/cpu*/cpufreq/scaling_governor; do echo powersave > $i; done
	  # aspm
	  echo powersave > /sys/module/pcie_aspm/parameters/policy
	  # kernel write mode
	  echo 5 > /proc/sys/vm/laptop_mode
	  echo 90 > /proc/sys/vm/dirty_ratio
	  echo 1 > /proc/sys/vm/dirty_background_ratio
	  echo 60000 > /proc/sys/vm/dirty_expire_centisecs
	  echo 60000 > /proc/sys/vm/dirty_writeback_centisecs
	  # disk powersave
	  hdparm -S 4 -B 254 -a 2048 /dev/sda &> /dev/null
      mount -o remount,commit=600 / &> /dev/null
      mount -o remount,commit=600 /home &> /dev/null
	  for i in /sys/class/scsi_host/host*/link_power_management_policy; do echo min_power > $i; done
	  # sound card powersave
	  echo 1 > /sys/module/snd_hda_intel/parameters/power_save
	  echo Y > /sys/module/snd_hda_intel/parameters/power_save_controller
	  # wlan0 powersave
	  iw dev wlp3s0 set power_save on &> /dev/null
	  # screen powersave
	  for i in /sys/class/backlight/acpi_video*/brightness; do echo 0 > $i; done
	  xset +dpms
	  xset dpms 0 0 120
	  ;;
	false) # Return to default on AC power
	  # bus
	  for i in /sys/bus/*/devices/*/power/control; do echo on > $i; done
	  # usb autosuspend
	  for i in /sys/bus/usb/devices/*/power/autosuspend; do echo 600 > $i; done
	  for i in /sys/bus/usb/devices/*/power/control; do echo auto > $i; done
	  # nmi_watchdog - disabled at kernel
	  #echo 1 > /proc/sys/kernel/nmi_watchdog
	  # cpu
	  for i in /sys/devices/system/cpu/cpu*/cpufreq/scaling_governor; do echo ondemand > $i; done
	  # aspm
	  echo default > /sys/module/pcie_aspm/parameters/policy
	  # kernel write mode
	  echo 0 > /proc/sys/vm/laptop_mode
	  echo 30 > /proc/sys/vm/dirty_ratio
	  echo 30 > /proc/sys/vm/dirty_background_ratio
	  echo 600 > /proc/sys/vm/dirty_expire_centisecs
	  echo 600 > /proc/sys/vm/dirty_writeback_centisecs
	  # disk powersave
	  hdparm -S 0 -B 254 -a 2048 /dev/sda &> /dev/null
      mount -o remount,commit=20 / &> /dev/null
      mount -o remount,commit=20 /home &> /dev/null
	  for i in /sys/class/scsi_host/host*/link_power_management_policy; do echo max_performance > $i; done
	  # sound card powersave
	  echo 0 > /sys/module/snd_hda_intel/parameters/power_save
	  echo N > /sys/module/snd_hda_intel/parameters/power_save_controller
	  # wlan0 powersave
	  iw dev wlp3s0 set power_save off &> /dev/null
	  # screen powersave
	  for i in /sys/class/backlight/acpi_video*/brightness; do echo 78 > $i; done
	  xset -dpms
	  ;;
esac
exit 0
